name: Android Build

on: pull_request

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Ktlint
        run: ./gradlew ktlintFormat

      - name: Build Project
        run: ./gradlew assemble
